### ISSUE TITLE
Create a list of the AutoHat tests we don't yet have

### ISSUE THREAD

**Issue by jviotti** [resin-io/resinos-tests#181]
As a way to evaluate if we can aim to completely replace that project

**Comment by jviotti** [comment]
@horia-delicoti Can you take care of this?

**Comment by horia-delicoti** [comment]
I created a list at the bottom of the file: [ResinOS Tests imported from autohat](https://docs.google.com/document/d/1SJOY3Ifa_qrMNt_qgJvdGwPE8E8Vk7EoytpY53DZVkQ/edit?usp=sharing)

**Comment by horia-delicoti** [comment]
A full list of all tests, testlodge and autohat are included [resinOS TestLodge Tests](https://docs.google.com/spreadsheets/d/1tUtQWrnj81zWjHXQJW9V1Sh5eqtbpVHsov48YYwoIjQ/edit#gid=0)
